DEFPTS/urls.py
from django.contrib import admin
from django.urls import include, path

from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('', include('polls.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
]

# urlpatterns += staticfiles_urlpatterns()

polls/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from .viewsPage import listeView, packsView, configView, catalogueAutomView, configAutomateView, accueilView
from .ListePTS import export


app_name = 'polls'
urlpatterns = [
    path('', accueilView.accueil, name='accueil'),
    path('catalogueAutom', catalogueAutomView.catalogueAutom, name='catalogueAutomView'),
    path('exportcatalogAutom/<str:filename>/<str:newName>', catalogueAutomView.download_catalogue, name='exportcatalogAutom'),

    path('accueilCataloguePacks', packsView.accueilCatalogPack, name='accueilCatalogPacks'),
    path('accueilCataloguePacks/TLG', packsView.packTLG, name='catalogPacksTLG'),
    path('exportcatalogPacksTLG/<str:filename>/<str:newName>', packsView.download_catalogue, name='exportcatalogPacksTLG'),
    path('accueilCataloguePacks/OPT', packsView.packOPT, name='catalogPacksOPT'),
    path('exportcatalogPacksOPT/<str:filename>/<str:newName>', packsView.download_catalogue, name='exportcatalogPacksOPT'),
    path('accueilCataloguePacks/TLR', packsView.packTLR, name='catalogPacksTLR'),
    path('exportcatalogPacksTLR/<str:filename>/<str:newName>', packsView.download_catalogue, name='exportcatalogPacksTLR'),



    path('chaufferie', listeView.genListeView, name='chaufferie'),
    path('liste/', listeView.listePts, name='listePts'),
    path('downloadfile/<str:filename>/<str:newName>', export.download_file, name='downloadfile'),

    path('config/', configView.newConfig, name='config'),
    path('configAutomate/', configAutomateView.newConfig, name='configAutomate'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/polls/models.py
from django.forms import ModelForm
from django.db import models

# Déclaration de l'objet chaufferie
class Chaufferie(models.Model):
    #Nombre de chaudière dans la chaufferie
    nbChaudiere = models.IntegerField()
    
    #Déclaration de la liste contenant les objets chaudières
    Chaudieres = []

    #Fonction permettant de créer les objets chaudières
    def creationChaudiere(self):
        self.Chaudieres.clear()
        for i in range(self.nbChaudiere):
            # Initialisation de la liste de chaudière pour affichage dans le formulaire
            # Le numéro de la chaudière est automatiquement renseignée
            # De base, une chaudière possède : 0 brûleur, 1 pompe, 1 vanne 2 voie
            self.Chaudieres.append(Chaudiere(num = i+1, nomChaud= "Chaudière " + str(i+1), nbBruleur = 0, nbV2V=1, nbPpe=1)) 

    #Fonction permettant d'actualiser les données chaudières
    def updateChaudiere(self, numero, nomChaud, nbBruleur, nbV2V, nbPpe):
        for chaud in self.Chaudieres:
            if chaud.num == numero :
                chaud.nomChaud = nomChaud
                chaud.nbBruleur = nbBruleur
                chaud.nbV2V = nbV2V
                chaud.nbPpe = nbPpe

#Déclaration de l'objet Chaudière
class Chaudiere(models.Model):
    num = models.IntegerField()
    nomChaud = models.CharField(max_length=200)
    nbBruleur = models.IntegerField()
    nbV2V = models.IntegerField()
    nbPpe = models.IntegerField()

polls/forms/forms.py
from django import forms
from ..models.Typology.modelsChaudiere import Chaufferie, Chaudiere

#Formulaire définissant le nombre de chaudières composant la chaufferie
class nbChaudForm(forms.ModelForm):
  class Meta:
    model = Chaufferie
    fields = ["nbChaudiere"]
    labels = {'nbChaudiere': "Nombre Chaudières"}

#Formulaire définissant les éléments qui composent chaque chaudière
class chaudForm(forms.ModelForm):
  class Meta:
    model = Chaudiere
    fields = ["nomChaud", "nbPpe", "nbV2V"]
    labels = {'nomChaud': "Nom", 'nbPpe': "Nombre de pompes", 'nbV2V':"Nombre de V2V"}

polls/forms/formsChaudiere.py
from django import forms
from ..models.Typology.modelsChaudiere import Chaufferie, Chaudiere

#Formulaire définissant le nombre de chaudières composant la chaufferie
class nbChaudForm(forms.ModelForm):
  class Meta:
    model = Chaufferie
    fields = ["nbChaudiere"]
    labels = {'nbChaudiere': "Nombre Chaudières"}

#Formulaire définissant les éléments qui composent chaque chaudière
class chaudForm(forms.ModelForm):
  class Meta:
    model = Chaudiere
    fields = ["nomChaud","nbPpe", "nbV2V"]
    labels = {'nomChaud': "Nom", 'nbPpe': "Nombre de pompes", 'nbV2V':"Nombre de V2V"}

    

polls/forms/formsLogIn.py
from django import forms

#Formulaire de connexion
class loginForm(forms.ModelForm):
  class Meta:
    fields = ["username", "password"]
    labels = {'username': "Nom d'utilisateur", 'password': "Mot de passe"}

src/polls/forms.py
from django import forms
from .models import Chaufferie, Chaudiere

#Formulaire définissant le nombre de chaudières composant la chaufferie
class nbChaudForm(forms.ModelForm):
  class Meta:
    model = Chaufferie
    fields = ["nbChaudiere"]
    labels = {'nbChaudiere': "Nombre Chaudières"}

#Formulaire définissant les éléments qui composent chaque chaudière
class chaudForm(forms.ModelForm):
  class Meta:
    model = Chaudiere
    fields = ["nomChaud","nbBruleur","nbPpe", "nbV2V"]
    labels = {'nomChaud': "Nom", 'nbBruleur': "Brûleur présent", 'nbPpe': "Nombre de pompes", 'nbV2V':"Nombre de V2V"}

polls/views.py
from django.shortcuts import render


#Page 1: Choix de la configuration
def IndexView(request):
    return render(request, 'polls/index.html')

polls/templates/polls/accueil.html
{% extends 'polls/headerNew.html' %}


{% block content %}
    </head>
    <body>
        <div class="first">
            <div class="first_row ">
                {% load static %}
                <img class="logo_sysco" src="{% static 'img/SyscoApp_logo.png' %}" alt="logo_sysco"/>
            </div>
            <nav class="navbar navbar-expand-lg navbar-dark navigation">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse navlibelle" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'polls:accueil' %}">ACCUEIL</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'polls:catalogueAutomView' %}">CATALOGUE AUTOMATE</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'polls:accueilCatalogPacks' %}">CATALOGUE PACK</a>
                        </li>
                    </ul>
                </div>
            </nav>
            <div class="second_row">
                <img class="fond_sysco" src="{% static 'img/SyscoApp_Accueil.jpg' %}" alt="fond_sysco"/>
            </div>  
        </div>

{% endblock %}

polls/templates/polls/accueilCataloguePacks.html
{% extends 'polls/headerNew.html' %}


{% block content %}
    </head>
    <body>
        <div class="first">
            <div class="first_row ">
                {% load static %}
                <img class="logo_sysco" src="{% static 'img/SyscoApp_logo.png' %}" alt="logo_sysco"/>
            </div>
            <nav class="navbar navbar-expand-lg navbar-dark navigation">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse navlibelle" id="navbarNav">
                    <ul class="navbar-nav">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'polls:accueil' %}">ACCUEIL</a>
                        </li>
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'polls:catalogueAutomView' %}">CATALOGUE AUTOMATE</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'polls:accueilCatalogPacks' %}">CATALOGUE PACK</a>
                        </li>
                    </ul>
                </div>
            </nav>
            <div class="second_row">
                <img class="fond_sysco" src="{% static 'img/SyscoApp_Accueil.jpg' %}" alt="fond_sysco"/>
            </div>  
            {% if user.is_authenticated %} 
            <div class="second_row_content">

                    <br>
                    <br>

                    <!-- AFFICHAGE DES PAGES CATALOGUES -->
                    <div class="accueilChoice">
                        <button style="background-color: #021766; border: 2px solid #021766; width:60%; border-radius: 20px;"><a style="color: white;" href="{% url 'polls:catalogPacksTLG' %}">TELEGESTION</a></button>
                        <br>
                        <button style="background-color: #021766; border: 2px solid #021766; width:60%; border-radius: 20px;"><a style="color: white;" href="{% url 'polls:catalogPacksOPT' %}">OPTIMISATION IoT</a></button>
                        <br>
                        <button style="background-color: #021766; border: 2px solid #021766; width:60%; border-radius: 20px;"><a style="color: white;" href="{% url 'polls:catalogPacksTLR' %}">TELERELEVE IoT</a></button>
                    </div>
                    
            </div>  

            {% else %}
            <div class="row three_row">
                <div class="col-12" style="display: flex; justify-content: center;font-size:xx-large;">
                    <p style="color:white">You are not logged in   =>  </p>
                    <a href="{% url 'login' %}" style="color:chocolate;"> Log In</a>
                </div>
            </div>
            {% endif %}
        </div>

{% endblock %}

polls/templates/polls/cataloguePacksOPT.html
{% extends 'polls/headerNew.html' %}

{% block content %}
    </head>
    <body>
        <div class="first">
            <div class="first_row absolute">
                {% load static %}
                <img class="logo_sysco" src="{% static 'img/SyscoApp_logo.png' %}" alt="logo_sysco"/>
            </div>
            <nav class="navbar navbar-expand-lg navbar-dark navigation">
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse navlibelle" id="navbarNav">
                    <ul class="navbar-nav">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'polls:accueil' %}">ACCUEIL</a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'polls:catalogueAutomView' %}">CATALOGUE AUTOMATE</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'polls:accueilCatalogPacks' %}">CATALOGUE PACK</a>
                    </li>
                    </ul>
                </div>
            </nav>
            <div class="second_row">
                {% load static %}
                <img class="fond_sysco" src="{% static 'img/SyscoApp_Accueil.jpg' %}" alt="fond_sysco"/>
            </div> 
            {% if user.is_authenticated %} 
            <div class="second_row_content">
                
                    <br>
                    <br>
                    <br>

                    <!-- AFFICHAGE DU TABLEAU DES CATALOGUES PACKS OPTIMISATION -->

                    <table class="table text-center" style="height: 20%;">
                        <thead>
                            <tr style="background-color: gray;">
                                <th class="itemES">Référence</th>
                                <th class="itemES">Nb IoT MAX</th>
                                <th class="itemES">Température Ambiant</th>
                                <th class="itemES">Température ECS</th>
                                <th class="itemES">Prix Passerelle</th>
                                <th class="itemES">Prix Température Ambiant</th>
                                <th class="itemES">Prix Température ECS</th>
                                <th class="itemES">Prix TOTAL</th>
                                {% if user.groups.first.name == "SYSCO" %}
                                <th style="width: 2%;">Action</th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody style="background-color: white;">
                            {% for p in catalogue %}
                                {% if packUPDATE == p.Reference %}
                                    <tr>
                                        <form action="" method="post" id="catalogueUPGform">
                                            {% csrf_token %}
                                            <td class="itemES"><input class="itemESNew" name="reference_Upd" id="reference_Upd" type="text" value="{{ p.Reference }}"></td>
                                            <td class="itemES"><input class="itemESNew" name="nbIOTmax_Upd" id="nbIOTmax_Upd" value="{{ p.nbIOTmax }}"></td>
                                            <td class="itemES"><input class="itemESNew" name="Tamb_Upd" id="Tamb_Upd" value="{{ p.Tamb }}"></td>
                                            <td class="itemES"><input class="itemESNew" name="TECS_Upd" id="TECS_Upd" value="{{ p.TECS }}"></td>
                                            <td class="itemES"><input class="itemESNew" name="pricePAS_Upd" id="pricePAS_Upd" value="{{ p.pricePAS }}">€</td>
                                            <td class="itemES"><input class="itemESNew" name="priceTamb_Upd" id="priceTamb_Upd" value="{{ p.priceTamb }}">€</td>
                                            <td class="itemES"><input class="itemESNew" name="priceTECS_Upd" id="priceTECS_Upd" value="{{ p.priceTECS }}">€</td>
                                            <td class="itemES"><input class="itemESNew" name="priceTOT_Upd" id="priceTOT_Upd" value="{{ p.priceTOT }}">€</td>
                                            <td style="width: 2%;align-items: center;">
                                                    <input type="hidden" name="form_type" value="PackOPTUPGform">
                                                    <button type="submit" class="btn btn-primary"name="ValidModif" id="ValidModif" value={{p.Reference}}>Valider</button>
                                            </td>
                                        </form>
                                    </tr>
                                {% else %}
                                    <tr>
                                        <td class="itemES"><p name="{{ p.Reference }}" id="{{ p.Reference }}" type="text" value="{{ p.Reference }}">{{ p.Reference }}</p></td>
                                        <td class="itemES"><p name="{{ p.nbIOTmax }}" id="{{ p.nbIOTmax }}">{{ p.nbIOTmax }}</p></td>
                                        <td class="itemES"><p name="{{ p.Tamb }}" id="{{ p.Tamb }}">{{ p.Tamb }}</p></td>
                                        <td class="itemES"><p name="{{ p.TECS }}" id="{{ p.TECS }}">{{ p.TECS }}</p></td>
                                        <td class="itemES"><p name="{{ p.pricePAS }}" id="{{ p.pricePAS }}">{{ p.pricePAS }} €</p></td>
                                        <td class="itemES"><p name="{{ p.priceTamb }}" id="{{ p.priceTamb }}">{{ p.priceTamb }} €</p></td>
                                        <td class="itemES"><p name="{{ p.priceTECS }}" id="{{ p.priceTECS }}">{{ p.priceTECS }} €</p></td>
                                        <td class="itemES"><p name="{{ p.priceTOT }}" id="{{ p.priceTOT }}">{{ p.priceTOT }} €</p></td>
                                        {% if user.groups.first.name == "SYSCO" %} 
                                        <td style="width: 2%;">
                                            <form action="" method="post" id="catalogueSupform" style="display: table-cell;align-self: center;">
                                                {% csrf_token %}
                                                <input type="hidden" name="form_type" value="catalogueSuppform">
                                                <button type="submit" class="btn btn-danger"name="Supp" id="Supp" value="{{p.Reference}}">Supprimer</button>
                                            </form>
                                            <form action="" method="post" id="catalogueModifform" style="display: table-cell;align-self: center;">
                                                {% csrf_token %}
                                                <input type="hidden" name="form_type" value="catalogueModifform">
                                                <button type="submit" class="btn btn-primary"name="Modif" id="Modif" value={{p.Reference}}>Modifier</button>
                                            </form>
                                        </td>
                                        {% endif %}
                                    </tr>
                                {% endif %}
                            {% endfor %}
                            {% if user.groups.first.name == "SYSCO" %}
                            <form action="" method="post" id="catalogueAddform">
                                {% csrf_token %}
                                <tr>
                                    <td class="itemES"><input class="itemESNew" name="reference_Add" id="reference_Add" type="text" value="référence"></td>
                                    <td class="itemES"><input class="itemESNew" name="nbIOTmax_Add" id="nbIOTmax_Add" type="number" value=0></td>
                                    <td class="itemES"><input class="itemESNew" name="Tamb_Add" id="Tamb_Add" type="number" value=0></td>
                                    <td class="itemES"><input class="itemESNew" name="TECS_Add" id="TECS_Add" type="number" value=0></td>
                                    <td class="itemES"><input class="itemESNew" name="pricePAS_Add" id="pricePAS_Add" type="number" step="0.01" value=0>€</td>
                                    <td class="itemES"><input class="itemESNew" name="priceTamb_Add" id="priceTamb_Add" type="number" step="0.01" value=0>€</td>
                                    <td class="itemES"><input class="itemESNew" name="priceTECS_Add" id="priceTECS_Add" type="number" step="0.01" value=0>€</td>
                                    <td class="itemES"><input class="itemESNew" name="priceTOT_Add" id="priceTOT_Add" type="number" step="0.01" value=0>€</td>
                                    <td style="width: 2%;display: table-cell;align-self: center;">
                                        <input type="hidden" name="form_type" value="PackOPTAddform">
                                        <button type="submit" class="btn btn-success"name="Add" id="Add" value=1>Ajout</button>
                                    </td> 
                                </tr>
                            </form>
                            {% endif %}
                        </tbody>
                    </table>  

                    <div style="color: chocolate;text-align: center;">
                        <span>
                            {% if catalogue.has_previous %}
                                <a href="?page=1" style="color: chocolate;">&laquo; Page 1</a>
                                <a href="?page={{ catalogue.previous_page_number }}" style="color: chocolate;">précédent</a>
                            {% endif %}
                    
                            <span class="current">
                                Page {{ catalogue.number }} of {{ catalogue.paginator.num_pages }}.
                            </span>
                    
                            {% if catalogue.has_next %}
                                <a href="?page={{ catalogue.next_page_number }}" style="color: chocolate;">suivant</a>
                                <a href="?page={{ catalogue.paginator.num_pages }}" style="color: chocolate;">Dernière page &raquo;</a>
                            {% endif %}
                        </span>
                    </div>
            </div> 

            <div class="row three_row">
                <div class="col">
                    <form action="" method="post" id="exportCatalogue" style="display: flex;justify-content: flex-start;">
                        {% csrf_token %}
                            <input type="hidden" name="form_type" value="exportCatalogue">
                            <button type="submit" class="btn btn-primary">Export Catalogue</button>
                    </form>
                </div>
                <div class="col">
                    <form action="" method="post" id="importCatalogue" class="form" enctype="multipart/form-data" style="display: flex;justify-content: flex-end;">
                        {% csrf_token %}
                            <input type="hidden" name="form_type" value="importCatalogue">
                            <input type="file" name="myfile" class="nomFileUpload">
                            <button type="submit" class="btn btn-success">Import Catalogue</button>
                    </form>
                </div>
            </div>   

            {% else %}
            <div class="row three_row">
                <div class="col-12" style="display: flex; justify-content: center;font-size:xx-large;">
                    <p style="color:white">You are not logged in   =>  </p>
                    <a href="{% url 'login' %}" style="color:chocolate;"> Log In</a>
                </div>
            </div>
            {% endif %}
        </div>



{% endblock %}

polls/templates/polls/configAutomate.html
{% extends 'polls/header.html' %}


{% block content %}
    {% if user.is_authenticated %}
        <div class="container-fluid">
            <h1 class="text-center">PACKS RETENUS</h1>
        </div>

        <span style="color:red">{{message}}</span>
        <br>
        <br>

        {% csrf_token %}
        <fieldset class="container-fluid mt-1 pb-1 border border-success rounded" {% if packTGOK.Reference == "" %} hidden {% endif %}>
            <div class="row">
                <legend class="text-center">PARTIE A - Automate TELEGESTION</legend>
            </div>

            <div class="container-fluid">
                <div class="row">
                    <table class="table text-center mt-2" style="width: 30%;">
                        <tbody>
                            <tr>
                                <td colspan="3" style="background-color: gray;font-size: 1.2em; color: white; vertical-align: middle;" width="50%">Automate WIT</td>
                            </tr>
                            {% for c in automateWIT %}
                            <tr>
                                <td style="background-color: gray;font-size: 1.2em; color: white; vertical-align: middle;" width="50%">{{ c.type }}</td>
                                <td class="packOKsec" style="vertical-align: middle;"><p name="{{ c.reference }}" id="{{ c.reference }}">{{ c.reference }}</p></td>
                                <td class="packOKsec" style="vertical-align: middle;"><p name="{{ c.prix }}" id="{{ c.prix }}">{{ c.prix }}€</p></td>
                            </tr>
                            {% endfor %}
                            <tr>
                                <td style="background-color: gray;font-size: 1.2em; color: white; vertical-align: middle;" width="50%">PRIX TOTAL MATERIEL</td>
                                <td class="packOKsec" colspan="2" style="vertical-align: middle;"><p name="{{ automatePrixWIT }}" id="{{ automatePrixWIT }}">{{ automatePrixWIT }}€</p></td>
                            </tr>
                            <tr>
                                <td style="background-color: gray;font-size: 1.2em; color: white; vertical-align: middle;" width="50%">PRIX PRESTATION PROGRAMMATION</td>
                                <td class="packOKsec" colspan="2" style="vertical-align: middle;"><p name="{{ PrestationPrix }}" id="{{ PrestationPrix }}">{{ PrestationPrix }}€</p></td>
                            </tr>
                            <tr>
                                <td style="background-color: gray;font-size: 1.2em; color: white; vertical-align: middle;" width="50%">PRIX TOTAL</td>
                                <td class="packOKsec" colspan="2" style="font-size: 1.3em;color:black;font-weight: bold;;"><p name="{{ coutTotalWIT }}" id="{{ coutTotalWIT }}">{{ coutTotalWIT }}€</p></td>
                            </tr>
                        </tbody>
                    </table>  
                    <table class="table text-center mt-2" style="width: 30%;">
                        <tbody>
                            <tr>
                                <td colspan="3" style="background-color: gray;font-size: 1.2em; color: white; vertical-align: middle;" width="50%">Automate DISTECH</td>
                            </tr>
                            {% for c in automateDISTECH %}
                            <tr>
                                <td style="background-color: gray;font-size: 1.2em; color: white; vertical-align: middle;" width="50%">{{ c.type }}</td>
                                <td class="packOKsec" style="vertical-align: middle;"><p name="{{ c.reference }}" id="{{ c.reference }}">{{ c.reference }}</p></td>
                                <td class="packOKsec" style="vertical-align: middle;"><p name="{{ c.prix }}" id="{{ c.prix }}">{{ c.prix }}€</p></td>
                            </tr>
                            {% endfor %}
                            <tr>
                                <td style="background-color: gray;font-size: 1.2em; color: white; vertical-align: middle;" width="50%">PRIX TOTAL MATERIEL</td>
                                <td class="packOKsec" colspan="2" style="vertical-align: middle;"><p name="{{ automatePrixDISTECH }}" id="{{ automatePrixDISTECH }}">{{ automatePrixDISTECH }}€</p></td>
                            </tr>
                            <tr>
                                <td style="background-color: gray;font-size: 1.2em; color: white; vertical-align: middle;" width="50%">PRIX PRESTATION PROGRAMMATION</td>
                                <td class="packOKsec" colspan="2" style="vertical-align: middle;"><p name="{{ PrestationPrix }}" id="{{ PrestationPrix }}">{{ PrestationPrix }}€</p></td>
                            </tr>
                            <tr>
                                <td style="background-color: gray;font-size: 1.2em; color: white; vertical-align: middle;" width="50%">PRIX TOTAL</td>
                                <td class="packOKsec" colspan="2" style="font-size: 1.3em;color:black;font-weight: bold; vertical-align: middle;"><p name="{{ coutTotalDISTECH }}" id="{{ coutTotalDISTECH }}">{{ coutTotalDISTECH }}€</p></td>
                            </tr>
                        </tbody>
                    </table>  
                </div>

            </div>
            
        </fieldset>
        <br>
    {% else %}
        <p>You are not logged in</p>
        <a href="{% url 'login' %}">Log In</a>
    {% endif %}
{% endblock %}

polls/templates/polls/header.html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

    <title>SYSCO PACK</title>

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/base.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/liste.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/pack.css' %}" media="screen">
    <link rel="stylesheet" href="{% static 'css/catalogueAutom.css' %}" media="screen">

    {% load django_bootstrap5 %}

    {% bootstrap_css %}

    {% bootstrap_javascript %}

    {% bootstrap_messages %}

    <script>
      function openNav() {
          document.getElementById("sideNavigation").style.width = "250px";
          document.getElementById("main").style.marginLeft = "250px";
      }
    
      function closeNav() {
          document.getElementById("sideNavigation").style.width = "0";
          document.getElementById("main").style.marginLeft = "0";
      }
    </script>
      
  </head>
  <body>
    <div id="sideNavigation" class="sidenav">
      <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
      {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">Log Out</a>
      {% else %}
        <a href="{% url 'login' %}">Log In</a>
      {% endif %}
      <a href="{% url 'polls:chaufferie' %}">1-Données d'entrée</a>
      <a href="{% url 'polls:listePts' %}">2-Liste de points générée</a>
      <a href="{% url 'polls:config' %}">3-Choix du pack</a>
      <a href="{% url 'polls:configAutomate' %}">4-Dimensionnement Automate</a>
      <div style="position: absolute; bottom: 0;">
        <a href="{% url 'polls:catalogueAutomView' %}">Catalogue Automate</a>
        <a href="{% url 'polls:packsView' %}">Packs SYSCO</a>
      </div>
    </div>
  
    <nav class="topnav">
      <a href="#" onclick="openNav()">
        <svg width="30" height="30" id="icoOpen">
            <path d="M0,5 30,5" stroke="#000" stroke-width="5"/>
            <path d="M0,14 30,14" stroke="#000" stroke-width="5"/>
            <path d="M0,23 30,23" stroke="#000" stroke-width="5"/>
        </svg>
      </a>
        <div class="row">
          <div class="col"></div>
          <div class="col"><h1 class="col" style="text-align: center;" >SYSCO APP</h1></div>
          <div class="col" style="text-align: right;" >
            <p>{{user.username}}</p>
            <p>{{user.groups.first.name}}</p>
          </div>
        </div>
    </nav>
  
    <div id="main">
  
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>   
  

  

polls/templates/polls/index.html
{% extends 'polls/header.html' %}

{% block content %}
    <ul>
        <!-- Choix de l'action -->
        <li><a href="/polls/chaufferie/">CREATION LISTE DE POINTS</a></li>
    </ul>
{% endblock %}